### Sai pass
POST http://localhost:8000/login
Authorization: Basic dXNlcjp3cm9uZw==

### Đúng pass
POST http://localhost:8000/login
Authorization: Basic dXNlcjp3cm9uZw=
### khong có header Authorization
GET http://localhost:8000/get-list

### có header Authorization
GET http://localhost:8000/get-list
Authorization: Basic dXNlcjoxMjM0

### submit info không có header Authorization
POST http://localhost:8000/submit-info
Content-Type: application/json

{
    "name": "KienDoTEST",
    "ip": "192.168.100.97",
    "port": "8004"
}


###
GET http://localhost:8000/get-list
Authorization: Basic dXNlcjoxMjM0

